version: '3'
services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./vault-volumes/logs:/vault/logs
      - ./vault-volumes/file:/vault/file
      - ./vault-volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json